/*
 * THIS FILE IS AUTOMATICALLY GENERATED
 *
 * Generator:     sensirion-driver-generator 1.1.0
 * Product:       sen63c
 * Model-Version: 1.0.0
 */

#include "sen63c_i2c.h"
#include "sensirion_common.h"
#include "sensirion_i2c.h"
#include "sensirion_i2c_hal.h"
#include "sensirion_test_setup.h"
#include <inttypes.h>
#include <stdio.h>

#define sensirion_hal_sleep_us sensirion_i2c_hal_sleep_usec

void print_byte_array(uint8_t* array, uint16_t len) {
    uint16_t i = 0;
    printf("0x");
    for (; i < len; i++) {
        printf("%02x", array[i]);
    }
}

TEST_GROUP (SEN63C_Tests) {
    void setup() {
        sen63c_init(0x6B);
    }
};

TEST (SEN63C_Tests, test_perform_forced_co2_recalibration1) {
    int16_t local_error = 0;
    uint16_t correction = 0;
    local_error = sen63c_perform_forced_co2_recalibration(600, &correction);
    CHECK_EQUAL_ZERO_TEXT(local_error, "perform_forced_co2_recalibration");
    printf("correction: %u\n", correction);
}

TEST (SEN63C_Tests, test_get_product_name1) {
    int16_t local_error = 0;
    uint8_t product_name[32] = {0};
    local_error = sen63c_get_product_name(product_name, 32);
    CHECK_EQUAL_ZERO_TEXT(local_error, "get_product_name");
    printf("product_name: ");
    print_byte_array(product_name, 32);
    printf("\n");
}

TEST (SEN63C_Tests, test_get_serial_number1) {
    int16_t local_error = 0;
    uint8_t serial_number[32] = {0};
    local_error = sen63c_get_serial_number(serial_number, 32);
    CHECK_EQUAL_ZERO_TEXT(local_error, "get_serial_number");
    printf("serial_number: ");
    print_byte_array(serial_number, 32);
    printf("\n");
}

TEST (SEN63C_Tests, test_device_reset1) {
    int16_t local_error = 0;
    local_error = sen63c_device_reset();
    CHECK_EQUAL_ZERO_TEXT(local_error, "device_reset");
}

TEST (SEN63C_Tests, test_start_fan_cleaning1) {
    int16_t local_error = 0;
    local_error = sen63c_start_fan_cleaning();
    CHECK_EQUAL_ZERO_TEXT(local_error, "start_fan_cleaning");
}

TEST (SEN63C_Tests, test_set_temperature_offset_parameters1) {
    int16_t local_error = 0;
    local_error = sen63c_set_temperature_offset_parameters(1, 10, 1, 0);
    CHECK_EQUAL_ZERO_TEXT(local_error, "set_temperature_offset_parameters");
}

TEST (SEN63C_Tests, test_set_temperature_acceleration_parameters1) {
    int16_t local_error = 0;
    local_error = sen63c_set_temperature_acceleration_parameters(1, 1, 1, 1);
    CHECK_EQUAL_ZERO_TEXT(local_error,
                          "set_temperature_acceleration_parameters");
}

TEST (SEN63C_Tests, test_set_co2_sensor_automatic_self_calibration1) {
    int16_t local_error = 0;
    local_error = sen63c_set_co2_sensor_automatic_self_calibration(0);
    CHECK_EQUAL_ZERO_TEXT(local_error,
                          "set_co2_sensor_automatic_self_calibration");
}

TEST (SEN63C_Tests, test_get_co2_sensor_automatic_self_calibration1) {
    int16_t local_error = 0;
    uint8_t padding = 0;
    bool status = false;
    local_error =
        sen63c_get_co2_sensor_automatic_self_calibration(&padding, &status);
    CHECK_EQUAL_ZERO_TEXT(local_error,
                          "get_co2_sensor_automatic_self_calibration");
    printf("padding: %u ", padding);
    printf("status: %d\n", status);
}

TEST (SEN63C_Tests, test_set_ambient_pressure1) {
    int16_t local_error = 0;
    local_error = sen63c_set_ambient_pressure(1013);
    CHECK_EQUAL_ZERO_TEXT(local_error, "set_ambient_pressure");
}

TEST (SEN63C_Tests, test_get_ambient_pressure1) {
    int16_t local_error = 0;
    uint16_t ambient_pressure = 0;
    local_error = sen63c_get_ambient_pressure(&ambient_pressure);
    CHECK_EQUAL_ZERO_TEXT(local_error, "get_ambient_pressure");
    printf("ambient_pressure: %u\n", ambient_pressure);
}

TEST (SEN63C_Tests, test_set_sensor_altitude1) {
    int16_t local_error = 0;
    local_error = sen63c_set_sensor_altitude(0);
    CHECK_EQUAL_ZERO_TEXT(local_error, "set_sensor_altitude");
}

TEST (SEN63C_Tests, test_get_sensor_altitude1) {
    int16_t local_error = 0;
    uint16_t altitude = 0;
    local_error = sen63c_get_sensor_altitude(&altitude);
    CHECK_EQUAL_ZERO_TEXT(local_error, "get_sensor_altitude");
    printf("altitude: %u\n", altitude);
}

TEST (SEN63C_Tests, test_activate_sht_heater1) {
    int16_t local_error = 0;
    local_error = sen63c_activate_sht_heater();
    CHECK_EQUAL_ZERO_TEXT(local_error, "activate_sht_heater");
}

TEST (SEN63C_Tests, test_read_device_status1) {
    int16_t local_error = 0;
    sen63c_device_status device_status = {.value = 0u};
    local_error = sen63c_read_device_status(&device_status);
    CHECK_EQUAL_ZERO_TEXT(local_error, "read_device_status");
    printf("device_status: %02x\n", device_status.value);
}

TEST (SEN63C_Tests, test_read_and_clear_device_status1) {
    int16_t local_error = 0;
    sen63c_device_status device_status = {.value = 0u};
    local_error = sen63c_read_and_clear_device_status(&device_status);
    CHECK_EQUAL_ZERO_TEXT(local_error, "read_and_clear_device_status");
    printf("device_status: %02x\n", device_status.value);
}

TEST (SEN63C_Tests, test_start_continuous_measurement1) {
    int16_t local_error = 0;
    uint8_t padding = 0;
    bool data_ready = false;
    uint16_t mass_concentration_pm1p0 = 0;
    uint16_t mass_concentration_pm2p5 = 0;
    uint16_t mass_concentration_pm4p0 = 0;
    uint16_t mass_concentration_pm10p0 = 0;
    int16_t ambient_humidity = 0;
    int16_t ambient_temperature = 0;
    uint16_t co2 = 0;
    uint16_t number_concentration_pm0p5 = 0;
    uint16_t number_concentration_pm1p0 = 0;
    uint16_t number_concentration_pm2p5 = 0;
    uint16_t number_concentration_pm4p0 = 0;
    uint16_t number_concentration_pm10p0 = 0;
    int16_t raw_humidity = 0;
    int16_t raw_temperature = 0;
    local_error = sen63c_start_continuous_measurement();
    CHECK_EQUAL_ZERO_TEXT(local_error, "start_continuous_measurement");
    local_error = sen63c_get_data_ready(&padding, &data_ready);
    CHECK_EQUAL_ZERO_TEXT(local_error, "get_data_ready");
    printf("padding: %u ", padding);
    printf("data_ready: %d\n", data_ready);
    local_error = sen63c_read_measured_values_as_integers(
        &mass_concentration_pm1p0, &mass_concentration_pm2p5,
        &mass_concentration_pm4p0, &mass_concentration_pm10p0,
        &ambient_humidity, &ambient_temperature, &co2);
    CHECK_EQUAL_ZERO_TEXT(local_error, "read_measured_values_as_integers");
    printf("mass_concentration_pm1p0: %u ", mass_concentration_pm1p0);
    printf("mass_concentration_pm2p5: %u ", mass_concentration_pm2p5);
    printf("mass_concentration_pm4p0: %u ", mass_concentration_pm4p0);
    printf("mass_concentration_pm10p0: %u ", mass_concentration_pm10p0);
    printf("ambient_humidity: %i ", ambient_humidity);
    printf("ambient_temperature: %i ", ambient_temperature);
    printf("co2: %u\n", co2);
    local_error = sen63c_read_number_concentration_values_as_integers(
        &number_concentration_pm0p5, &number_concentration_pm1p0,
        &number_concentration_pm2p5, &number_concentration_pm4p0,
        &number_concentration_pm10p0);
    CHECK_EQUAL_ZERO_TEXT(local_error,
                          "read_number_concentration_values_as_integers");
    printf("number_concentration_pm0p5: %u ", number_concentration_pm0p5);
    printf("number_concentration_pm1p0: %u ", number_concentration_pm1p0);
    printf("number_concentration_pm2p5: %u ", number_concentration_pm2p5);
    printf("number_concentration_pm4p0: %u ", number_concentration_pm4p0);
    printf("number_concentration_pm10p0: %u\n", number_concentration_pm10p0);
    local_error =
        sen63c_read_measured_raw_values(&raw_humidity, &raw_temperature);
    CHECK_EQUAL_ZERO_TEXT(local_error, "read_measured_raw_values");
    printf("raw_humidity: %i ", raw_humidity);
    printf("raw_temperature: %i\n", raw_temperature);
    local_error = sen63c_set_temperature_offset_parameters(1, 10, 1, 0);
    CHECK_EQUAL_ZERO_TEXT(local_error, "set_temperature_offset_parameters");
    local_error = sen63c_stop_measurement();
    CHECK_EQUAL_ZERO_TEXT(local_error, "stop_measurement");
}
